// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetShield.Inventory.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetShield.Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260904005021_Inventory_AddCredentialProfiles")]
    partial class Inventory_AddCredentialProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetShield.Inventory.Credentials.CredentialProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthAlgorithm")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("auth_algorithm");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<byte[]>("MaterialCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("material_ciphertext");

                    b.Property<DateTimeOffset>("MaterialUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("material_updated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("PrivacyAlgorithm")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("privacy_algorithm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.Property<byte[]>("WrappedDataKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_data_key");

                    b.HasKey("Id")
                        .HasName("pk_credential_profiles");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_credential_profiles_deleted_at");

                    b.HasIndex("KeyId")
                        .HasDatabaseName("ix_credential_profiles_key_id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_credential_profiles_normalized_name_live")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_credential_profiles_created_at_id");

                    b.ToTable("credential_profiles", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Credentials.DeviceCredentialProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CredentialProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_profile_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_credential_profiles");

                    b.HasIndex("CredentialProfileId")
                        .HasDatabaseName("ix_device_credential_profiles_credential_profile_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_credential_profiles_device_id");

                    b.HasIndex("DeviceId", "CredentialProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_credential_profiles_device_id_credential_profile_id");

                    b.ToTable("device_credential_profiles", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("criticality");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("environment");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("os_version");

                    b.Property<string>("Owner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner");

                    b.Property<IPAddress>("PrimaryIpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("primary_ip_address");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Site")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("site");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vendor");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_devices_deleted_at");

                    b.HasIndex("Hostname")
                        .HasDatabaseName("ix_devices_hostname");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_devices_created_at_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("NetShield.Platform.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("NetShield.Inventory.Credentials.DeviceCredentialProfile", b =>
                {
                    b.HasOne("NetShield.Inventory.Credentials.CredentialProfile", null)
                        .WithMany()
                        .HasForeignKey("CredentialProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_credential_profiles_credential_profiles_credential_p");

                    b.HasOne("NetShield.Inventory.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_credential_profiles_devices_device_id");
                });
#pragma warning restore 612, 618
        }
    }
}
