// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetShield.Inventory.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetShield.Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetShield.Inventory.Collector.CollectorJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CredentialProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_profile_id");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("detail");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lease_token");

                    b.Property<string>("LeasedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("leased_by");

                    b.Property<DateTimeOffset?>("LeasedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leased_until");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Outcome")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_collector_jobs");

                    b.HasIndex("CredentialProfileId")
                        .HasDatabaseName("ix_collector_jobs_credential_profile_id");

                    b.HasIndex("DeviceId", "CreatedAt")
                        .HasDatabaseName("ix_collector_jobs_device_id_created_at");

                    b.HasIndex("Status", "DueAt")
                        .HasDatabaseName("ix_collector_jobs_claimable");

                    b.ToTable("collector_jobs", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Collector.CollectorNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("Running")
                        .HasColumnType("integer")
                        .HasColumnName("running");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_collectors");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_collectors_last_seen_at");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_collectors_normalized_name");

                    b.ToTable("collectors", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Credentials.CredentialProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthAlgorithm")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("auth_algorithm");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<byte[]>("MaterialCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("material_ciphertext");

                    b.Property<DateTimeOffset>("MaterialUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("material_updated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("PrivacyAlgorithm")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("privacy_algorithm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.Property<byte[]>("WrappedDataKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_data_key");

                    b.HasKey("Id")
                        .HasName("pk_credential_profiles");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_credential_profiles_deleted_at");

                    b.HasIndex("KeyId")
                        .HasDatabaseName("ix_credential_profiles_key_id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_credential_profiles_normalized_name_live")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_credential_profiles_created_at_id");

                    b.ToTable("credential_profiles", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Credentials.DeviceCredentialProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CredentialProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_profile_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_credential_profiles");

                    b.HasIndex("CredentialProfileId")
                        .HasDatabaseName("ix_device_credential_profiles_credential_profile_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_credential_profiles_device_id");

                    b.HasIndex("DeviceId", "CredentialProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_credential_profiles_device_id_credential_profile_id");

                    b.ToTable("device_credential_profiles", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("criticality");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("environment");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("os_version");

                    b.Property<string>("Owner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner");

                    b.Property<IPAddress>("PrimaryIpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("primary_ip_address");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Site")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("site");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vendor");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_devices_deleted_at");

                    b.HasIndex("Hostname")
                        .HasDatabaseName("ix_devices_hostname");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_devices_created_at_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Discovery.DeviceFingerprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("InterfaceCount")
                        .HasColumnType("integer")
                        .HasColumnName("interface_count");

                    b.Property<bool>("InterfacesTruncated")
                        .HasColumnType("boolean")
                        .HasColumnName("interfaces_truncated");

                    b.Property<Guid?>("LastAppliedJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_applied_job_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastWalkAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_walk_at");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("os_version");

                    b.PrimitiveCollection<string[]>("OverriddenFields")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("overridden_fields");

                    b.Property<bool>("ReducedCapability")
                        .HasColumnType("boolean")
                        .HasColumnName("reduced_capability");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("serial_number");

                    b.Property<string>("SysContact")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_contact");

                    b.Property<string>("SysDescr")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("sys_descr");

                    b.Property<string>("SysLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_location");

                    b.Property<string>("SysName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_name");

                    b.Property<string>("SysObjectId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_object_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double?>("UptimeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_seconds");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vendor");

                    b.HasKey("Id")
                        .HasName("pk_device_fingerprints");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_fingerprints_device_id");

                    b.ToTable("device_fingerprints", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Discovery.DeviceInterface", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AdminStatus")
                        .HasColumnType("integer")
                        .HasColumnName("admin_status");

                    b.Property<string>("Alias")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("alias");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<int>("IfIndex")
                        .HasColumnType("integer")
                        .HasColumnName("if_index");

                    b.Property<int?>("InterfaceType")
                        .HasColumnType("integer")
                        .HasColumnName("interface_type");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int?>("Mtu")
                        .HasColumnType("integer")
                        .HasColumnName("mtu");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("OperStatus")
                        .HasColumnType("integer")
                        .HasColumnName("oper_status");

                    b.Property<string>("PhysicalAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("physical_address");

                    b.Property<long?>("SpeedBitsPerSecond")
                        .HasColumnType("bigint")
                        .HasColumnName("speed_bits_per_second");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_interfaces");

                    b.HasIndex("DeviceId", "IfIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_device_interfaces_device_id_if_index");

                    b.ToTable("device_interfaces", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Discovery.DiscoveryCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<IPAddress>("Address")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<Guid>("FirstSeenRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_seen_run_id");

                    b.Property<double?>("LastRttMilliseconds")
                        .HasColumnType("double precision")
                        .HasColumnName("last_rtt_milliseconds");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("LastSeenRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_seen_run_id");

                    b.Property<Guid?>("PromotedDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("promoted_device_id");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("TimesSeen")
                        .HasColumnType("integer")
                        .HasColumnName("times_seen");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_discovery_candidates");

                    b.HasIndex("Status", "LastSeenAt", "Id")
                        .HasDatabaseName("ix_discovery_candidates_status_last_seen_at_id");

                    b.ToTable("discovery_candidates", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Discovery.DiscoveryIgnore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cidr")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cidr");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_discovery_ignores");

                    b.HasIndex("Cidr")
                        .IsUnique()
                        .HasDatabaseName("ix_discovery_ignores_cidr");

                    b.ToTable("discovery_ignores", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Discovery.DiscoveryRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AddressCount")
                        .HasColumnType("bigint")
                        .HasColumnName("address_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("Exclusions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("exclusions");

                    b.Property<int>("ExistingDeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("existing_device_count");

                    b.Property<int>("IgnoredCount")
                        .HasColumnType("integer")
                        .HasColumnName("ignored_count");

                    b.Property<int>("JobCount")
                        .HasColumnType("integer")
                        .HasColumnName("job_count");

                    b.Property<int>("JobsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("jobs_completed");

                    b.Property<int>("JobsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("jobs_failed");

                    b.Property<int>("KnownCandidateCount")
                        .HasColumnType("integer")
                        .HasColumnName("known_candidate_count");

                    b.Property<int>("NewCandidateCount")
                        .HasColumnType("integer")
                        .HasColumnName("new_candidate_count");

                    b.PrimitiveCollection<string[]>("Ranges")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ranges");

                    b.Property<int>("RespondedCount")
                        .HasColumnType("integer")
                        .HasColumnName("responded_count");

                    b.Property<Guid>("SeedId")
                        .HasColumnType("uuid")
                        .HasColumnName("seed_id");

                    b.Property<string>("SeedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("seed_name");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_discovery_runs");

                    b.HasIndex("SeedId", "Status")
                        .HasDatabaseName("ix_discovery_runs_seed_id_status");

                    b.HasIndex("StartedAt", "Id")
                        .HasDatabaseName("ix_discovery_runs_started_at_id");

                    b.ToTable("discovery_runs", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Discovery.DiscoveryRunHost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<IPAddress>("Address")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("address");

                    b.Property<Guid?>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("outcome");

                    b.Property<double?>("RttMilliseconds")
                        .HasColumnType("double precision")
                        .HasColumnName("rtt_milliseconds");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_discovery_run_hosts");

                    b.HasIndex("RunId", "Id")
                        .HasDatabaseName("ix_discovery_run_hosts_run_id_id");

                    b.ToTable("discovery_run_hosts", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Discovery.DiscoveryRunJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AddressCount")
                        .HasColumnType("integer")
                        .HasColumnName("address_count");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid>("CollectorJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_job_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("first_address");

                    b.Property<string>("LastAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_address");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<bool?>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_discovery_run_jobs");

                    b.HasIndex("CollectorJobId")
                        .IsUnique()
                        .HasDatabaseName("ix_discovery_run_jobs_collector_job_id");

                    b.HasIndex("RunId", "AppliedAt")
                        .HasDatabaseName("ix_discovery_run_jobs_run_id_applied_at");

                    b.ToTable("discovery_run_jobs", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Discovery.DiscoverySeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.PrimitiveCollection<string[]>("Exclusions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("exclusions");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.PrimitiveCollection<string[]>("Ranges")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ranges");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_discovery_seeds");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_discovery_seeds_deleted_at");

                    b.HasIndex("Enabled", "NextRunAt")
                        .HasDatabaseName("ix_discovery_seeds_enabled_next_run_at");

                    b.ToTable("discovery_seeds", (string)null);
                });

            modelBuilder.Entity("NetShield.Inventory.Reachability.DeviceReachability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid?>("LastAppliedJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_applied_job_id");

                    b.Property<DateTimeOffset?>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("last_error");

                    b.Property<double?>("LastLossPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("last_loss_percent");

                    b.Property<DateTimeOffset?>("LastProbeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_probe_at");

                    b.Property<double?>("LastRttMilliseconds")
                        .HasColumnType("double precision")
                        .HasColumnName("last_rtt_milliseconds");

                    b.Property<DateTimeOffset>("NextProbeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_probe_at");

                    b.Property<int>("PendingObservations")
                        .HasColumnType("integer")
                        .HasColumnName("pending_observations");

                    b.Property<string>("PendingState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("pending_state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_reachability");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_reachability_device_id");

                    b.HasIndex("NextProbeAt")
                        .HasDatabaseName("ix_device_reachability_next_probe_at");

                    b.ToTable("device_reachability", (string)null);
                });

            modelBuilder.Entity("NetShield.Platform.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("NetShield.Inventory.Credentials.DeviceCredentialProfile", b =>
                {
                    b.HasOne("NetShield.Inventory.Credentials.CredentialProfile", null)
                        .WithMany()
                        .HasForeignKey("CredentialProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_credential_profiles_credential_profiles_credential_p");

                    b.HasOne("NetShield.Inventory.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_credential_profiles_devices_device_id");
                });
#pragma warning restore 612, 618
        }
    }
}
