/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ThreatsRouteImport } from './routes/threats'
import { Route as VulnerabilitiesRouteImport } from './routes/vulnerabilities'
import { Route as AdministrationIndexRouteImport } from './routes/administration.index'
import { Route as AdministrationAuditLogRouteImport } from './routes/administration.audit-log'
import { Route as AdministrationBackupRestoreRouteImport } from './routes/administration.backup-restore'
import { Route as AdministrationLicenseRouteImport } from './routes/administration.license'
import { Route as AdministrationRolesRouteImport } from './routes/administration.roles'
import { Route as AdministrationSystemHealthRouteImport } from './routes/administration.system-health'
import { Route as AdministrationUsersRouteImport } from './routes/administration.users'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsAlertActivityRouteImport } from './routes/reports.alert-activity'
import { Route as ReportsAvailabilityRouteImport } from './routes/reports.availability'
import { Route as ReportsBandwidthRouteImport } from './routes/reports.bandwidth'
import { Route as ReportsComplianceRouteImport } from './routes/reports.compliance'
import { Route as ReportsInventoryRouteImport } from './routes/reports.inventory'
import { Route as ReportsVulnerabilityRouteImport } from './routes/reports.vulnerability'
import { Route as SecurityIndexRouteImport } from './routes/security.index'
import { Route as SecurityFindingsRouteImport } from './routes/security.findings'
import { Route as SecurityPostureRouteImport } from './routes/security.posture'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatsRoute = ThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const VulnerabilitiesRoute = VulnerabilitiesRouteImport.update({
  id: '/vulnerabilities',
  path: '/vulnerabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationIndexRoute = AdministrationIndexRouteImport.update({
  id: '/administration/',
  path: '/administration/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationAuditLogRoute = AdministrationAuditLogRouteImport.update({
  id: '/administration/audit-log',
  path: '/administration/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationBackupRestoreRoute =
  AdministrationBackupRestoreRouteImport.update({
    id: '/administration/backup-restore',
    path: '/administration/backup-restore',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationLicenseRoute = AdministrationLicenseRouteImport.update({
  id: '/administration/license',
  path: '/administration/license',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRolesRoute = AdministrationRolesRouteImport.update({
  id: '/administration/roles',
  path: '/administration/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationSystemHealthRoute =
  AdministrationSystemHealthRouteImport.update({
    id: '/administration/system-health',
    path: '/administration/system-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationUsersRoute = AdministrationUsersRouteImport.update({
  id: '/administration/users',
  path: '/administration/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAlertActivityRoute = ReportsAlertActivityRouteImport.update({
  id: '/reports/alert-activity',
  path: '/reports/alert-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAvailabilityRoute = ReportsAvailabilityRouteImport.update({
  id: '/reports/availability',
  path: '/reports/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsBandwidthRoute = ReportsBandwidthRouteImport.update({
  id: '/reports/bandwidth',
  path: '/reports/bandwidth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsComplianceRoute = ReportsComplianceRouteImport.update({
  id: '/reports/compliance',
  path: '/reports/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsInventoryRoute = ReportsInventoryRouteImport.update({
  id: '/reports/inventory',
  path: '/reports/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsVulnerabilityRoute = ReportsVulnerabilityRouteImport.update({
  id: '/reports/vulnerability',
  path: '/reports/vulnerability',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityFindingsRoute = SecurityFindingsRouteImport.update({
  id: '/security/findings',
  path: '/security/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityPostureRoute = SecurityPostureRouteImport.update({
  id: '/security/posture',
  path: '/security/posture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/clients': typeof ClientsRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/logs': typeof LogsRoute
  '/network': typeof NetworkRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/threats': typeof ThreatsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/administration/audit-log': typeof AdministrationAuditLogRoute
  '/administration/backup-restore': typeof AdministrationBackupRestoreRoute
  '/administration/license': typeof AdministrationLicenseRoute
  '/administration/roles': typeof AdministrationRolesRoute
  '/administration/system-health': typeof AdministrationSystemHealthRoute
  '/administration/users': typeof AdministrationUsersRoute
  '/reports/alert-activity': typeof ReportsAlertActivityRoute
  '/reports/availability': typeof ReportsAvailabilityRoute
  '/reports/bandwidth': typeof ReportsBandwidthRoute
  '/reports/compliance': typeof ReportsComplianceRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/vulnerability': typeof ReportsVulnerabilityRoute
  '/security/findings': typeof SecurityFindingsRoute
  '/security/posture': typeof SecurityPostureRoute
  '/administration/': typeof AdministrationIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/security/': typeof SecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/clients': typeof ClientsRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/logs': typeof LogsRoute
  '/network': typeof NetworkRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/threats': typeof ThreatsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/administration/audit-log': typeof AdministrationAuditLogRoute
  '/administration/backup-restore': typeof AdministrationBackupRestoreRoute
  '/administration/license': typeof AdministrationLicenseRoute
  '/administration/roles': typeof AdministrationRolesRoute
  '/administration/system-health': typeof AdministrationSystemHealthRoute
  '/administration/users': typeof AdministrationUsersRoute
  '/reports/alert-activity': typeof ReportsAlertActivityRoute
  '/reports/availability': typeof ReportsAvailabilityRoute
  '/reports/bandwidth': typeof ReportsBandwidthRoute
  '/reports/compliance': typeof ReportsComplianceRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/vulnerability': typeof ReportsVulnerabilityRoute
  '/security/findings': typeof SecurityFindingsRoute
  '/security/posture': typeof SecurityPostureRoute
  '/administration': typeof AdministrationIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/security': typeof SecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/clients': typeof ClientsRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/logs': typeof LogsRoute
  '/network': typeof NetworkRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/threats': typeof ThreatsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/administration/audit-log': typeof AdministrationAuditLogRoute
  '/administration/backup-restore': typeof AdministrationBackupRestoreRoute
  '/administration/license': typeof AdministrationLicenseRoute
  '/administration/roles': typeof AdministrationRolesRoute
  '/administration/system-health': typeof AdministrationSystemHealthRoute
  '/administration/users': typeof AdministrationUsersRoute
  '/reports/alert-activity': typeof ReportsAlertActivityRoute
  '/reports/availability': typeof ReportsAvailabilityRoute
  '/reports/bandwidth': typeof ReportsBandwidthRoute
  '/reports/compliance': typeof ReportsComplianceRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/vulnerability': typeof ReportsVulnerabilityRoute
  '/security/findings': typeof SecurityFindingsRoute
  '/security/posture': typeof SecurityPostureRoute
  '/administration/': typeof AdministrationIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/security/': typeof SecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/clients'
    | '/compliance'
    | '/dashboard'
    | '/devices'
    | '/logs'
    | '/network'
    | '/overview'
    | '/policies'
    | '/threats'
    | '/vulnerabilities'
    | '/administration/audit-log'
    | '/administration/backup-restore'
    | '/administration/license'
    | '/administration/roles'
    | '/administration/system-health'
    | '/administration/users'
    | '/reports/alert-activity'
    | '/reports/availability'
    | '/reports/bandwidth'
    | '/reports/compliance'
    | '/reports/inventory'
    | '/reports/vulnerability'
    | '/security/findings'
    | '/security/posture'
    | '/administration/'
    | '/reports/'
    | '/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/clients'
    | '/compliance'
    | '/dashboard'
    | '/devices'
    | '/logs'
    | '/network'
    | '/overview'
    | '/policies'
    | '/threats'
    | '/vulnerabilities'
    | '/administration/audit-log'
    | '/administration/backup-restore'
    | '/administration/license'
    | '/administration/roles'
    | '/administration/system-health'
    | '/administration/users'
    | '/reports/alert-activity'
    | '/reports/availability'
    | '/reports/bandwidth'
    | '/reports/compliance'
    | '/reports/inventory'
    | '/reports/vulnerability'
    | '/security/findings'
    | '/security/posture'
    | '/administration'
    | '/reports'
    | '/security'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/clients'
    | '/compliance'
    | '/dashboard'
    | '/devices'
    | '/logs'
    | '/network'
    | '/overview'
    | '/policies'
    | '/threats'
    | '/vulnerabilities'
    | '/administration/audit-log'
    | '/administration/backup-restore'
    | '/administration/license'
    | '/administration/roles'
    | '/administration/system-health'
    | '/administration/users'
    | '/reports/alert-activity'
    | '/reports/availability'
    | '/reports/bandwidth'
    | '/reports/compliance'
    | '/reports/inventory'
    | '/reports/vulnerability'
    | '/security/findings'
    | '/security/posture'
    | '/administration/'
    | '/reports/'
    | '/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ClientsRoute: typeof ClientsRoute
  ComplianceRoute: typeof ComplianceRoute
  DashboardRoute: typeof DashboardRoute
  DevicesRoute: typeof DevicesRoute
  LogsRoute: typeof LogsRoute
  NetworkRoute: typeof NetworkRoute
  OverviewRoute: typeof OverviewRoute
  PoliciesRoute: typeof PoliciesRoute
  ThreatsRoute: typeof ThreatsRoute
  VulnerabilitiesRoute: typeof VulnerabilitiesRoute
  AdministrationAuditLogRoute: typeof AdministrationAuditLogRoute
  AdministrationBackupRestoreRoute: typeof AdministrationBackupRestoreRoute
  AdministrationLicenseRoute: typeof AdministrationLicenseRoute
  AdministrationRolesRoute: typeof AdministrationRolesRoute
  AdministrationSystemHealthRoute: typeof AdministrationSystemHealthRoute
  AdministrationUsersRoute: typeof AdministrationUsersRoute
  ReportsAlertActivityRoute: typeof ReportsAlertActivityRoute
  ReportsAvailabilityRoute: typeof ReportsAvailabilityRoute
  ReportsBandwidthRoute: typeof ReportsBandwidthRoute
  ReportsComplianceRoute: typeof ReportsComplianceRoute
  ReportsInventoryRoute: typeof ReportsInventoryRoute
  ReportsVulnerabilityRoute: typeof ReportsVulnerabilityRoute
  SecurityFindingsRoute: typeof SecurityFindingsRoute
  SecurityPostureRoute: typeof SecurityPostureRoute
  AdministrationIndexRoute: typeof AdministrationIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threats': {
      id: '/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof ThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vulnerabilities': {
      id: '/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof VulnerabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/': {
      id: '/administration/'
      path: '/administration'
      fullPath: '/administration/'
      preLoaderRoute: typeof AdministrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/audit-log': {
      id: '/administration/audit-log'
      path: '/administration/audit-log'
      fullPath: '/administration/audit-log'
      preLoaderRoute: typeof AdministrationAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/backup-restore': {
      id: '/administration/backup-restore'
      path: '/administration/backup-restore'
      fullPath: '/administration/backup-restore'
      preLoaderRoute: typeof AdministrationBackupRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/license': {
      id: '/administration/license'
      path: '/administration/license'
      fullPath: '/administration/license'
      preLoaderRoute: typeof AdministrationLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/roles': {
      id: '/administration/roles'
      path: '/administration/roles'
      fullPath: '/administration/roles'
      preLoaderRoute: typeof AdministrationRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/system-health': {
      id: '/administration/system-health'
      path: '/administration/system-health'
      fullPath: '/administration/system-health'
      preLoaderRoute: typeof AdministrationSystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/users': {
      id: '/administration/users'
      path: '/administration/users'
      fullPath: '/administration/users'
      preLoaderRoute: typeof AdministrationUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/alert-activity': {
      id: '/reports/alert-activity'
      path: '/reports/alert-activity'
      fullPath: '/reports/alert-activity'
      preLoaderRoute: typeof ReportsAlertActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/availability': {
      id: '/reports/availability'
      path: '/reports/availability'
      fullPath: '/reports/availability'
      preLoaderRoute: typeof ReportsAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/bandwidth': {
      id: '/reports/bandwidth'
      path: '/reports/bandwidth'
      fullPath: '/reports/bandwidth'
      preLoaderRoute: typeof ReportsBandwidthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/compliance': {
      id: '/reports/compliance'
      path: '/reports/compliance'
      fullPath: '/reports/compliance'
      preLoaderRoute: typeof ReportsComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/inventory': {
      id: '/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof ReportsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/vulnerability': {
      id: '/reports/vulnerability'
      path: '/reports/vulnerability'
      fullPath: '/reports/vulnerability'
      preLoaderRoute: typeof ReportsVulnerabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/findings': {
      id: '/security/findings'
      path: '/security/findings'
      fullPath: '/security/findings'
      preLoaderRoute: typeof SecurityFindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/posture': {
      id: '/security/posture'
      path: '/security/posture'
      fullPath: '/security/posture'
      preLoaderRoute: typeof SecurityPostureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ClientsRoute: ClientsRoute,
  ComplianceRoute: ComplianceRoute,
  DashboardRoute: DashboardRoute,
  DevicesRoute: DevicesRoute,
  LogsRoute: LogsRoute,
  NetworkRoute: NetworkRoute,
  OverviewRoute: OverviewRoute,
  PoliciesRoute: PoliciesRoute,
  ThreatsRoute: ThreatsRoute,
  VulnerabilitiesRoute: VulnerabilitiesRoute,
  AdministrationAuditLogRoute: AdministrationAuditLogRoute,
  AdministrationBackupRestoreRoute: AdministrationBackupRestoreRoute,
  AdministrationLicenseRoute: AdministrationLicenseRoute,
  AdministrationRolesRoute: AdministrationRolesRoute,
  AdministrationSystemHealthRoute: AdministrationSystemHealthRoute,
  AdministrationUsersRoute: AdministrationUsersRoute,
  ReportsAlertActivityRoute: ReportsAlertActivityRoute,
  ReportsAvailabilityRoute: ReportsAvailabilityRoute,
  ReportsBandwidthRoute: ReportsBandwidthRoute,
  ReportsComplianceRoute: ReportsComplianceRoute,
  ReportsInventoryRoute: ReportsInventoryRoute,
  ReportsVulnerabilityRoute: ReportsVulnerabilityRoute,
  SecurityFindingsRoute: SecurityFindingsRoute,
  SecurityPostureRoute: SecurityPostureRoute,
  AdministrationIndexRoute: AdministrationIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SecurityIndexRoute: SecurityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
