/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppSplatRouteImport } from './routes/_app.$'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppComplianceRouteImport } from './routes/_app.compliance'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppNetworkRouteImport } from './routes/_app.network'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppPoliciesRouteImport } from './routes/_app.policies'
import { Route as AppThreatsRouteImport } from './routes/_app.threats'
import { Route as AppVulnerabilitiesRouteImport } from './routes/_app.vulnerabilities'
import { Route as AppAdministrationIndexRouteImport } from './routes/_app.administration.index'
import { Route as AppAdministrationAuditLogRouteImport } from './routes/_app.administration.audit-log'
import { Route as AppAdministrationBackupRestoreRouteImport } from './routes/_app.administration.backup-restore'
import { Route as AppAdministrationLicenseRouteImport } from './routes/_app.administration.license'
import { Route as AppAdministrationRolesRouteImport } from './routes/_app.administration.roles'
import { Route as AppAdministrationSystemHealthRouteImport } from './routes/_app.administration.system-health'
import { Route as AppAdministrationUsersRouteImport } from './routes/_app.administration.users'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppReportsAlertActivityRouteImport } from './routes/_app.reports.alert-activity'
import { Route as AppReportsAvailabilityRouteImport } from './routes/_app.reports.availability'
import { Route as AppReportsBandwidthRouteImport } from './routes/_app.reports.bandwidth'
import { Route as AppReportsComplianceRouteImport } from './routes/_app.reports.compliance'
import { Route as AppReportsInventoryRouteImport } from './routes/_app.reports.inventory'
import { Route as AppReportsVulnerabilityRouteImport } from './routes/_app.reports.vulnerability'
import { Route as AppSecurityIndexRouteImport } from './routes/_app.security.index'
import { Route as AppSecurityFindingsRouteImport } from './routes/_app.security.findings'
import { Route as AppSecurityPostureRouteImport } from './routes/_app.security.posture'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesRoute = AppPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppThreatsRoute = AppThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => AppRoute,
} as any)
const AppVulnerabilitiesRoute = AppVulnerabilitiesRouteImport.update({
  id: '/vulnerabilities',
  path: '/vulnerabilities',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministrationIndexRoute = AppAdministrationIndexRouteImport.update({
  id: '/administration/',
  path: '/administration/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministrationAuditLogRoute =
  AppAdministrationAuditLogRouteImport.update({
    id: '/administration/audit-log',
    path: '/administration/audit-log',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationBackupRestoreRoute =
  AppAdministrationBackupRestoreRouteImport.update({
    id: '/administration/backup-restore',
    path: '/administration/backup-restore',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationLicenseRoute =
  AppAdministrationLicenseRouteImport.update({
    id: '/administration/license',
    path: '/administration/license',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationRolesRoute = AppAdministrationRolesRouteImport.update({
  id: '/administration/roles',
  path: '/administration/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministrationSystemHealthRoute =
  AppAdministrationSystemHealthRouteImport.update({
    id: '/administration/system-health',
    path: '/administration/system-health',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationUsersRoute = AppAdministrationUsersRouteImport.update({
  id: '/administration/users',
  path: '/administration/users',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsAlertActivityRoute = AppReportsAlertActivityRouteImport.update({
  id: '/reports/alert-activity',
  path: '/reports/alert-activity',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsAvailabilityRoute = AppReportsAvailabilityRouteImport.update({
  id: '/reports/availability',
  path: '/reports/availability',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsBandwidthRoute = AppReportsBandwidthRouteImport.update({
  id: '/reports/bandwidth',
  path: '/reports/bandwidth',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsComplianceRoute = AppReportsComplianceRouteImport.update({
  id: '/reports/compliance',
  path: '/reports/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsInventoryRoute = AppReportsInventoryRouteImport.update({
  id: '/reports/inventory',
  path: '/reports/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsVulnerabilityRoute = AppReportsVulnerabilityRouteImport.update({
  id: '/reports/vulnerability',
  path: '/reports/vulnerability',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityIndexRoute = AppSecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityFindingsRoute = AppSecurityFindingsRouteImport.update({
  id: '/security/findings',
  path: '/security/findings',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityPostureRoute = AppSecurityPostureRouteImport.update({
  id: '/security/posture',
  path: '/security/posture',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/alerts': typeof AppAlertsRoute
  '/clients': typeof AppClientsRoute
  '/compliance': typeof AppComplianceRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/logs': typeof AppLogsRoute
  '/network': typeof AppNetworkRoute
  '/overview': typeof AppOverviewRoute
  '/policies': typeof AppPoliciesRoute
  '/threats': typeof AppThreatsRoute
  '/vulnerabilities': typeof AppVulnerabilitiesRoute
  '/administration/audit-log': typeof AppAdministrationAuditLogRoute
  '/administration/backup-restore': typeof AppAdministrationBackupRestoreRoute
  '/administration/license': typeof AppAdministrationLicenseRoute
  '/administration/roles': typeof AppAdministrationRolesRoute
  '/administration/system-health': typeof AppAdministrationSystemHealthRoute
  '/administration/users': typeof AppAdministrationUsersRoute
  '/reports/alert-activity': typeof AppReportsAlertActivityRoute
  '/reports/availability': typeof AppReportsAvailabilityRoute
  '/reports/bandwidth': typeof AppReportsBandwidthRoute
  '/reports/compliance': typeof AppReportsComplianceRoute
  '/reports/inventory': typeof AppReportsInventoryRoute
  '/reports/vulnerability': typeof AppReportsVulnerabilityRoute
  '/security/findings': typeof AppSecurityFindingsRoute
  '/security/posture': typeof AppSecurityPostureRoute
  '/administration/': typeof AppAdministrationIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/security/': typeof AppSecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/alerts': typeof AppAlertsRoute
  '/clients': typeof AppClientsRoute
  '/compliance': typeof AppComplianceRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/logs': typeof AppLogsRoute
  '/network': typeof AppNetworkRoute
  '/overview': typeof AppOverviewRoute
  '/policies': typeof AppPoliciesRoute
  '/threats': typeof AppThreatsRoute
  '/vulnerabilities': typeof AppVulnerabilitiesRoute
  '/administration/audit-log': typeof AppAdministrationAuditLogRoute
  '/administration/backup-restore': typeof AppAdministrationBackupRestoreRoute
  '/administration/license': typeof AppAdministrationLicenseRoute
  '/administration/roles': typeof AppAdministrationRolesRoute
  '/administration/system-health': typeof AppAdministrationSystemHealthRoute
  '/administration/users': typeof AppAdministrationUsersRoute
  '/reports/alert-activity': typeof AppReportsAlertActivityRoute
  '/reports/availability': typeof AppReportsAvailabilityRoute
  '/reports/bandwidth': typeof AppReportsBandwidthRoute
  '/reports/compliance': typeof AppReportsComplianceRoute
  '/reports/inventory': typeof AppReportsInventoryRoute
  '/reports/vulnerability': typeof AppReportsVulnerabilityRoute
  '/security/findings': typeof AppSecurityFindingsRoute
  '/security/posture': typeof AppSecurityPostureRoute
  '/administration': typeof AppAdministrationIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/security': typeof AppSecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/compliance': typeof AppComplianceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/policies': typeof AppPoliciesRoute
  '/_app/threats': typeof AppThreatsRoute
  '/_app/vulnerabilities': typeof AppVulnerabilitiesRoute
  '/_app/administration/audit-log': typeof AppAdministrationAuditLogRoute
  '/_app/administration/backup-restore': typeof AppAdministrationBackupRestoreRoute
  '/_app/administration/license': typeof AppAdministrationLicenseRoute
  '/_app/administration/roles': typeof AppAdministrationRolesRoute
  '/_app/administration/system-health': typeof AppAdministrationSystemHealthRoute
  '/_app/administration/users': typeof AppAdministrationUsersRoute
  '/_app/reports/alert-activity': typeof AppReportsAlertActivityRoute
  '/_app/reports/availability': typeof AppReportsAvailabilityRoute
  '/_app/reports/bandwidth': typeof AppReportsBandwidthRoute
  '/_app/reports/compliance': typeof AppReportsComplianceRoute
  '/_app/reports/inventory': typeof AppReportsInventoryRoute
  '/_app/reports/vulnerability': typeof AppReportsVulnerabilityRoute
  '/_app/security/findings': typeof AppSecurityFindingsRoute
  '/_app/security/posture': typeof AppSecurityPostureRoute
  '/_app/administration/': typeof AppAdministrationIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/security/': typeof AppSecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/$'
    | '/alerts'
    | '/clients'
    | '/compliance'
    | '/dashboard'
    | '/devices'
    | '/logs'
    | '/network'
    | '/overview'
    | '/policies'
    | '/threats'
    | '/vulnerabilities'
    | '/administration/audit-log'
    | '/administration/backup-restore'
    | '/administration/license'
    | '/administration/roles'
    | '/administration/system-health'
    | '/administration/users'
    | '/reports/alert-activity'
    | '/reports/availability'
    | '/reports/bandwidth'
    | '/reports/compliance'
    | '/reports/inventory'
    | '/reports/vulnerability'
    | '/security/findings'
    | '/security/posture'
    | '/administration/'
    | '/reports/'
    | '/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/$'
    | '/alerts'
    | '/clients'
    | '/compliance'
    | '/dashboard'
    | '/devices'
    | '/logs'
    | '/network'
    | '/overview'
    | '/policies'
    | '/threats'
    | '/vulnerabilities'
    | '/administration/audit-log'
    | '/administration/backup-restore'
    | '/administration/license'
    | '/administration/roles'
    | '/administration/system-health'
    | '/administration/users'
    | '/reports/alert-activity'
    | '/reports/availability'
    | '/reports/bandwidth'
    | '/reports/compliance'
    | '/reports/inventory'
    | '/reports/vulnerability'
    | '/security/findings'
    | '/security/posture'
    | '/administration'
    | '/reports'
    | '/security'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/change-password'
    | '/login'
    | '/_app/$'
    | '/_app/alerts'
    | '/_app/clients'
    | '/_app/compliance'
    | '/_app/dashboard'
    | '/_app/devices'
    | '/_app/logs'
    | '/_app/network'
    | '/_app/overview'
    | '/_app/policies'
    | '/_app/threats'
    | '/_app/vulnerabilities'
    | '/_app/administration/audit-log'
    | '/_app/administration/backup-restore'
    | '/_app/administration/license'
    | '/_app/administration/roles'
    | '/_app/administration/system-health'
    | '/_app/administration/users'
    | '/_app/reports/alert-activity'
    | '/_app/reports/availability'
    | '/_app/reports/bandwidth'
    | '/_app/reports/compliance'
    | '/_app/reports/inventory'
    | '/_app/reports/vulnerability'
    | '/_app/security/findings'
    | '/_app/security/posture'
    | '/_app/administration/'
    | '/_app/reports/'
    | '/_app/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies': {
      id: '/_app/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AppPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threats': {
      id: '/_app/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof AppThreatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vulnerabilities': {
      id: '/_app/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof AppVulnerabilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/': {
      id: '/_app/administration/'
      path: '/administration'
      fullPath: '/administration/'
      preLoaderRoute: typeof AppAdministrationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/audit-log': {
      id: '/_app/administration/audit-log'
      path: '/administration/audit-log'
      fullPath: '/administration/audit-log'
      preLoaderRoute: typeof AppAdministrationAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/backup-restore': {
      id: '/_app/administration/backup-restore'
      path: '/administration/backup-restore'
      fullPath: '/administration/backup-restore'
      preLoaderRoute: typeof AppAdministrationBackupRestoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/license': {
      id: '/_app/administration/license'
      path: '/administration/license'
      fullPath: '/administration/license'
      preLoaderRoute: typeof AppAdministrationLicenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/roles': {
      id: '/_app/administration/roles'
      path: '/administration/roles'
      fullPath: '/administration/roles'
      preLoaderRoute: typeof AppAdministrationRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/system-health': {
      id: '/_app/administration/system-health'
      path: '/administration/system-health'
      fullPath: '/administration/system-health'
      preLoaderRoute: typeof AppAdministrationSystemHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/users': {
      id: '/_app/administration/users'
      path: '/administration/users'
      fullPath: '/administration/users'
      preLoaderRoute: typeof AppAdministrationUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/alert-activity': {
      id: '/_app/reports/alert-activity'
      path: '/reports/alert-activity'
      fullPath: '/reports/alert-activity'
      preLoaderRoute: typeof AppReportsAlertActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/availability': {
      id: '/_app/reports/availability'
      path: '/reports/availability'
      fullPath: '/reports/availability'
      preLoaderRoute: typeof AppReportsAvailabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/bandwidth': {
      id: '/_app/reports/bandwidth'
      path: '/reports/bandwidth'
      fullPath: '/reports/bandwidth'
      preLoaderRoute: typeof AppReportsBandwidthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/compliance': {
      id: '/_app/reports/compliance'
      path: '/reports/compliance'
      fullPath: '/reports/compliance'
      preLoaderRoute: typeof AppReportsComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/inventory': {
      id: '/_app/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof AppReportsInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/vulnerability': {
      id: '/_app/reports/vulnerability'
      path: '/reports/vulnerability'
      fullPath: '/reports/vulnerability'
      preLoaderRoute: typeof AppReportsVulnerabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/': {
      id: '/_app/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof AppSecurityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/findings': {
      id: '/_app/security/findings'
      path: '/security/findings'
      fullPath: '/security/findings'
      preLoaderRoute: typeof AppSecurityFindingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/posture': {
      id: '/_app/security/posture'
      path: '/security/posture'
      fullPath: '/security/posture'
      preLoaderRoute: typeof AppSecurityPostureRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppClientsRoute: typeof AppClientsRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppLogsRoute: typeof AppLogsRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPoliciesRoute: typeof AppPoliciesRoute
  AppThreatsRoute: typeof AppThreatsRoute
  AppVulnerabilitiesRoute: typeof AppVulnerabilitiesRoute
  AppAdministrationAuditLogRoute: typeof AppAdministrationAuditLogRoute
  AppAdministrationBackupRestoreRoute: typeof AppAdministrationBackupRestoreRoute
  AppAdministrationLicenseRoute: typeof AppAdministrationLicenseRoute
  AppAdministrationRolesRoute: typeof AppAdministrationRolesRoute
  AppAdministrationSystemHealthRoute: typeof AppAdministrationSystemHealthRoute
  AppAdministrationUsersRoute: typeof AppAdministrationUsersRoute
  AppReportsAlertActivityRoute: typeof AppReportsAlertActivityRoute
  AppReportsAvailabilityRoute: typeof AppReportsAvailabilityRoute
  AppReportsBandwidthRoute: typeof AppReportsBandwidthRoute
  AppReportsComplianceRoute: typeof AppReportsComplianceRoute
  AppReportsInventoryRoute: typeof AppReportsInventoryRoute
  AppReportsVulnerabilityRoute: typeof AppReportsVulnerabilityRoute
  AppSecurityFindingsRoute: typeof AppSecurityFindingsRoute
  AppSecurityPostureRoute: typeof AppSecurityPostureRoute
  AppAdministrationIndexRoute: typeof AppAdministrationIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSecurityIndexRoute: typeof AppSecurityIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppClientsRoute: AppClientsRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppLogsRoute: AppLogsRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPoliciesRoute: AppPoliciesRoute,
  AppThreatsRoute: AppThreatsRoute,
  AppVulnerabilitiesRoute: AppVulnerabilitiesRoute,
  AppAdministrationAuditLogRoute: AppAdministrationAuditLogRoute,
  AppAdministrationBackupRestoreRoute: AppAdministrationBackupRestoreRoute,
  AppAdministrationLicenseRoute: AppAdministrationLicenseRoute,
  AppAdministrationRolesRoute: AppAdministrationRolesRoute,
  AppAdministrationSystemHealthRoute: AppAdministrationSystemHealthRoute,
  AppAdministrationUsersRoute: AppAdministrationUsersRoute,
  AppReportsAlertActivityRoute: AppReportsAlertActivityRoute,
  AppReportsAvailabilityRoute: AppReportsAvailabilityRoute,
  AppReportsBandwidthRoute: AppReportsBandwidthRoute,
  AppReportsComplianceRoute: AppReportsComplianceRoute,
  AppReportsInventoryRoute: AppReportsInventoryRoute,
  AppReportsVulnerabilityRoute: AppReportsVulnerabilityRoute,
  AppSecurityFindingsRoute: AppSecurityFindingsRoute,
  AppSecurityPostureRoute: AppSecurityPostureRoute,
  AppAdministrationIndexRoute: AppAdministrationIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSecurityIndexRoute: AppSecurityIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
